### ISSUE TITLE
Improve C++ support

### ISSUE THREAD

**Issue by jvoisin** [jvoisin/fortify-headers#31]
As said by Dmytro Hrybenko:

> consider adding a hyrum's law buster until you are ready to support c++
```cpp
#ifdef __cplusplus
#error this library only supports C
#endif
```

**Comment by thesamesam** [comment]
I think this is likely to be a pain in the posterior when patching or otherwise instructing (e.g. config files in `/etc/clang`) the compiler to use the headers.

**Comment by jvoisin** [comment]
Yeah, I'm not convinced either. I think a warning might be too annoying as well.

Shall we silently do nothing instead? Most (all?) libc++ implementations have their own hardening anyway.

**Comment by q66** [comment]
the fortify-headers i have in chimera work fine with c++, so this is a regression and a blocker

**Comment by q66** [comment]
"c++ implementations have their own hardening" is irrelevant here, fortify is supposed to harden the C standard library interfaces which are widely used from C++, and disabling this in C++ == effectively dehardening

**Comment by jvoisin** [comment]
As said by @ssbr

> It looks like this is meant to be usable from c++ code, but the static inline is an ODR trap in C++ (but not C). Can I FR that it only use static inline in C?
>
> If you call any of the FORTIFY_INLINE functions from an inline function in C++, and include the header defining that inline function in more than one TU, the resulting program has undefined behaviour.
>
> Unlike C++, C has more relaxed rules on inline functions, and static inline is not dangerous in C at all -- it even has a specific meaning. See https://en.cppreference.com/w/c/language/inline, especially its notes on the differences between the two languages:
>
> > The inline keyword was adopted from C++, but in C++, if a function is declared inline, it must be declared inline in every translation unit, and also every definition of an inline function must be exactly the same (in C, the definitions may be different, and depending on the differences only results in unspecified behavior). On the other hand, C++ allows non-const function-local statics and all function-local statics from different definitions of an inline function are the same in C++ but distinct in C.
>
> Best as I understand the two languages, a C static inline function is kind of like a C++ inline function, and a C++ static inline function is kind of like a C inline function (except with an added ODR trap).

**Comment by ssbr** [comment]
Yeah, that solves the problem for C++. I think it isn't _quite_ obviously true that things should be fine, because the situation in C is still potentially risky: using a `static` function from an `inline` function included in two TUs is still unspecified behavior, which can be bad, depending on exactly what that behavior is and what you would need it to be.

I think the reason to drop the `static` only in C++, and keep it in C, would be:

1. C programmers tend to use `static inline` or `static` in headers, rather than `inline`, meaning issues are rare.
2. While the behavior is still unspecified for users that use `inline` functions in headers, the behavior on all known implementations are reasonable and correspond to what you want. (For example, perhaps it picks one implementation arbitrarily, but you're OK with the false positives/negatives that result from how that interacts with e.g. the use of `__builtin_object_size` etc., and it is still better than having no results at all due to non-`static` `inline`.)

Both of these statements seem to have a good chance of being true, because of the history of C: `inline` came in C99, long after `static`, and so many headers use `static` already. Either users, or the compilers, or both, already have to deal with the old existing `static` functions in headers. And so maybe it makes sense to continue using `static` in C, and one can expect things to work OK in the face of this.

If, on the other hand, C programs tend to use `inline` (sans `static`) a lot, and the concrete behaviors that result are quite undesirable, then it would make sense to me to drop `static` in **both** C and C++.

---

C++ doesn't have these properties -- `inline` has been in there some time, with strict rules, where mixing the two inappropriately is UB and compilers do arbitrarily bad things with it in practice. I would remove `static` from C++, regardless of whether it's kept in C.

(Even if the behaviors that seem to come up in practice are reasonable, relying on UB is super not ideal, and this isn't one of the forms of UB that clang/gcc/etc. actually want to support, the way e.g. strict aliasing violation is supported via compiler flags.)

**Comment by q66** [comment]
you can't drop static in headers in C, because with plain non-static inline C forces you to have exactly one definition of the function body in one TU as far as I understand it

**Comment by q66** [comment]
ah, no, the rule is that when using plain inline in C, you're supposed to put an extern inline in a single TU to effectively tell the compiler the TU to bind the external function to

**Comment by q66** [comment]
anyway, let's change `fortify-headers.h` to have an `#ifdef __cplusplus` which will use a non-static inline declaration for clang, and we should probably be okay

**Comment by ssbr** [comment]
Ah yeah, to be clear, I'm a C++ programmer, not a C programmer -- my C knowledge is limited to what I'm reading on cppreference (a C++ website, lol).

It sounds like `static inline` really should be fine, then. Removing it only in C++ sounds good to me!
